 -- 일반 사용자 계정을 만들 수 있도록 내부 설정 변경
ALTER session set "_ORACLE_SCRIPT"=TRUE;

-- 프로젝트용 계정 생성
CREATE USER final_project IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- 권한 부여
GRANT CONNECT, RESOURCE TO final_project;

-----------------------------------------------------------


-- 회원 정보 테이블
CREATE TABLE member(
	mno		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 회원 번호
	id		VARCHAR2(50) NOT NULL UNIQUE,									-- 아이디
	pw		VARCHAR2(50) NOT NULL,											-- 비밀번호
	name	VARCHAR2(50) NOT NULL,											-- 이름
	phone	VARCHAR2(20),													-- 전화번호
	email 	VARCHAR2(100) NOT NULL,											-- 이메일
	addr	VARCHAR2(200),													-- 주소
	info	char(1), 														-- 개인 정보 이용 동의 여부
	status	char(1) DEFAULT 'Y'												-- 계정 활성화 여부(기본: 'Y', 탈퇴: 'N')
);

-- 전체 조회
SELECT * FROM member;

-- 테이블 제거
DROP TABLE member PURGE;

-- 도서 정보 테이블
CREATE TABLE book(
	bno				NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 도서 번호
	title			VARCHAR2(200) NOT NULL,												-- 제목
	author			VARCHAR2(50) NOT NULL,												-- 저자
	publisher		VARCHAR2(100) NOT NULL,												-- 발행 기관
	p_date			NUMBER(4),															-- 발행 연도
	cover			VARCHAR2(200),														-- 표지 이미지 경로
	is_available	VARCHAR2(20) DEFAULT 'AVAILABLE',									-- 대출 가능 여부(기본: 대출 가능, 대출 중인 경우: 불가능 'UNAVAILABLE')
	b_status		char(1) DEFAULT 'Y'													-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM book;

-- 테이블 제거
DROP TABLE book PURGE;

-- 도서 대출 테이블
CREATE TABLE book_loan(
	loan_no			NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 대출 번호
	bno				NUMBER NOT NULL REFERENCES book(bno),								-- 도서 번호
	user_id			VARCHAR2(50) NOT NULL REFERENCES member(id),						-- 대출자 아이디
	loan_status		VARCHAR2(50) DEFAULT 'BORROWED',									-- 대출 상태(기본: 대출 중, 반납 시 'RETURNED' / 추후 예약 기능 추가 가능)
	borrow_date 	DATE DEFAULT SYSDATE NOT NULL,										-- 대출일
	return_date 	DATE																-- 반납일
);

-- 전체 조회
SELECT * FROM book_loan;

-- 테이블 제거
DROP TABLE book_loan PURGE;

-- 이달의 도서 테이블
CREATE TABLE book_of_the_month(
	bom_no		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 번호 PK	
	bno			NUMBER REFERENCES book(bno),										-- 도서 번호
	title		VARCHAR2(200) NOT NULL,												-- 제목
	author		VARCHAR2(50) NOT NULL,												-- 저자
	publisher	VARCHAR2(100) NOT NULL,												-- 발행 기관
	p_date		NUMBER(4),															-- 발행 연도
	cover		VARCHAR2(200),														-- 표지 이미지 경로
	bom_status	char(1) DEFAULT 'Y'													-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM book_of_the_month;

-- 테이블 제거
DROP TABLE book_of_the_month PURGE;

-- 스터디룸 정보 테이블
CREATE TABLE studyroom(
	sno		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 스터디룸 번호
	s_name	VARCHAR2(50)														-- 스터디룸 이름(스터디룸 1, 스터디룸 2, ... 스터디룸 6 / 추후 스터디룸 추가 가능) 
);

-- 전체 조회
SELECT * FROM studyroom;

-- 테이블 제거
DROP TABLE studyroom PURGE;

-- 스터디룸 예약 테이블
CREATE TABLE studyroom_reservation(
	rno		 		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 예약 번호
	sno		 		NUMBER NOT NULL REFERENCES studyroom(sno),						-- 스터디룸 번호
	user_id	 		VARCHAR2(50) NOT NULL REFERENCES member(id),					-- 예약자 아이디
	user_name 		VARCHAR2(50) NOT NULL,											-- 예약자 이름
	reserve_date	DATE NOT NULL,													-- 예약 희망일
	apply_date		DATE DEFAULT SYSDATE NOT NULL,									-- 예약 신청일
	status			VARCHAR2(50) DEFAULT 'PENDING'									-- 예약 상태(기본: 대기 /승인, 거절, 취소) 
);

-- 전체 조회
SELECT * FROM studyroom_reservation;

-- 테이블 제거
DROP TABLE studyroom_reservation PURGE;

-- 공지 사항 저장 테이블
CREATE TABLE notice(
	nno				NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 공지 번호
	n_title			VARCHAR2(200) NOT NULL,											-- 제목
	n_author		VARCHAR2(50) NOT NULL,											-- 작성자 이름(관리자)
	n_content		CLOB,															-- 공지 내용
	n_create_date	DATE DEFAULT SYSDATE NOT NULL,									-- 작성 시간
	n_status		char(1) DEFAULT 'Y'												-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM notice;

-- 테이블 제거
DROP TABLE notice PURGE;

-- 건의 사항 게시글 저장 테이블
CREATE TABLE suggestion(
	sug_no			NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 건의 게시글 번호
	s_title			VARCHAR2(200) NOT NULL,											-- 제목
	s_userid		VARCHAR2(50) NOT NULL REFERENCES member(id),					-- 작성자 아이디
	s_author		VARCHAR2(50) NOT NULL,											-- 작성자 이름
	s_content		CLOB,															-- 건의 내용
	s_create_date	DATE DEFAULT SYSDATE NOT NULL,									-- 작성 시간
	s_update_date	DATE,															-- 수정 시간
	s_status		char(1) DEFAULT 'Y'												-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM suggestion;

-- 테이블 제거
DROP TABLE suggestion PURGE;

-- 건의 사항 댓글 저장 테이블
CREATE TABLE suggestion_reply(
	rpl_no			NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 
	sug_no			NUMBER NOT NULL REFERENCES suggestion(sug_no),					-- 건의 게시글 번호
	user_id			VARCHAR2(50) NOT NULL REFERENCES member(id),											-- 댓글 작성자 아이디(관리자 or 글 작성자)
	content			CLOB,															-- 댓글 내용
	rpl_create_date DATE DEFAULT SYSDATE NOT NULL,									-- 작성 시간
	rpl_update_date	DATE,															-- 수정 시간
	rpl_status		char(1) DEFAULT 'Y'												-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM suggestion_reply;

-- 테이블 제거
DROP TABLE suggestion_reply PURGE;

-- 도서관 정보 테이블
CREATE TABLE library_info(
	library_name	VARCHAR2(100) NOT NULL,			-- 도서관 이름
	tel				VARCHAR2(50) NOT NULL,			-- 전화 번호
	location		VARCHAR2(200) NOT NULL,			-- 위치
	operating_hour	VARCHAR2(100) NOT NULL,			-- 이용 시간
	closed_date		VARCHAR2(200) NOT NULL			-- 휴관일 정보
);

-- 전체 조회
SELECT * FROM library_info;

-- 테이블 제거
DROP TABLE library_info PURGE;


-- 테스트용 도서 데이터 입력

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('조금 망한 사랑', '김지연', '문학동네', '2024', 'images/1.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('초승달 엔딩 클럽', '조예은', '위즈덤하우스', '2024', 'images/2.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('낙엽 다이빙', '강은옥', '위즈덤하우스', '2023', 'images/3.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('스테로이드 인류 : 기적과 죽음의 연대기', '백승만', '히포크라테스', '2024', 'images/4.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('첫 여름, 완주', '김금희', '무제', '2025', 'images/5.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('스파클', '최현진', '창비', '2025', 'images/6.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('여름방학 숙제 조작단', '이진하', '사계절', '2021', 'images/7.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('얼음산 빙수 가게', '정현진', '올리', '2024', 'images/8.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('야외 수영장', '빌 그멜링 지음 (전은경 옮김)', '라임', '2021', 'images/9.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('어떤 토끼', '고정순', '반달', '2024', 'images/10.jpg');

INSERT INTO book(title, author, publisher, p_date, cover)
VALUES('해든 분식', '동지아', '문학동네', '2024', 'images/11.jpg');

-- 테스트용 이달의 도서 데이터 입력
INSERT INTO book_of_the_month(bno, title, author, publisher, p_date, cover)
VALUES('2', '초승달 엔딩 클럽', '조예은', '위즈덤하우스', '2024', 'images/2.jpg');

INSERT INTO book_of_the_month(bno, title, author, publisher, p_date, cover)
VALUES('5', '첫 여름, 완주', '김금희', '무제', '2025', 'images/5.jpg');

INSERT INTO book_of_the_month(bno, title, author, publisher, p_date, cover)
VALUES('6', '스파클', '최현진', '창비', '2025', 'images/6.jpg');


------------------- 회원 등록
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('minsu89', 'pw1234', '김민수', '01023456789', 'minsu89@example.com', '서울특별시 강남구 테헤란로 123');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('seoyeon22', 'pw1234', '이서연', '01087654321', 'seoyeon22@example.com', '경기도 성남시 분당구 수내동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('jihun07', 'pw1234', '박지훈', '01011112222', 'jihun07@example.com', '부산광역시 해운대구 우동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('yerin95', 'pw1234', '최예린', '01033334444', 'yerin95@example.com', '대구광역시 수성구 만촌동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('wooyoung01', 'pw1234', '정우영', '01055556666', 'wooyoung01@example.com', '인천광역시 연수구 송도동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('jieun94', 'pw1234', '한지은', '01077778888', 'jieun94@example.com', '광주광역시 서구 화정동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('junho88', 'pw1234', '송준호', '01099990000', 'junho88@example.com', '대전광역시 서구 둔산동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('dahyun02', 'pw1234', '김다현', '01022223333', 'dahyun02@example.com', '울산광역시 남구 신정동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('doyoon77', 'pw1234', '이도윤', '01044445555', 'doyoon77@example.com', '강원도 춘천시 효자동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('minji09', 'pw1234', '장민지', '01066667777', 'minji09@example.com', '제주특별자치도 제주시 노형동');

INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('yuri91', 'pw1234', '안유리', '01010102020', 'yuri91@example.com', '서울특별시 마포구 상암동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('sangho85', 'pw1234', '이상호', '01030304040', 'sangho85@example.com', '서울특별시 서초구 방배동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('eunji93', 'pw1234', '조은지', '01050506060', 'eunji93@example.com', '경기도 용인시 수지구 죽전동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('yeonju90', 'pw1234', '김연주', '01070708080', 'yeonju90@example.com', '서울특별시 송파구 문정동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('jiho88', 'pw1234', '손지호', '01090901111', 'jiho88@example.com', '경기도 고양시 덕양구 행신동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('mina96', 'pw1234', '박민아', '01012121313', 'mina96@example.com', '부산광역시 북구 화명동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('sungmin84', 'pw1234', '전성민', '01014141515', 'sungmin84@example.com', '서울특별시 강동구 성내동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('haneul92', 'pw1234', '공하늘', '01016161717', 'haneul92@example.com', '경기도 성남시 판교동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('jisoo01', 'pw1234', '강지수', '01018181919', 'jisoo01@example.com', '전라북도 전주시 효자동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('dasom97', 'pw1234', '윤다솜', '01020202121', 'dasom97@example.com', '경기도 안양시 동안구 관양동');

INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('gayoung89', 'pw1234', '김가영', '01022222323', 'gayoung89@example.com', '서울특별시 강남구 압구정동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('sanghyuk88', 'pw1234', '박상혁', '01024242525', 'sanghyuk88@example.com', '서울특별시 용산구 이태원동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('sumin99', 'pw1234', '차수민', '01026262727', 'sumin99@example.com', '충청남도 천안시 두정동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('hyewon95', 'pw1234', '정혜원', '01028282929', 'hyewon95@example.com', '서울특별시 종로구 청운동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('junhyuk86', 'pw1234', '이준혁', '01030303131', 'junhyuk86@example.com', '서울특별시 강서구 등촌동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('dain01', 'pw1234', '김다인', '01032323333', 'dain01@example.com', '경기도 수원시 영통구 원천동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('sungwoo83', 'pw1234', '홍성우', '01034343535', 'sungwoo83@example.com', '경기도 부천시 중동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('soohyun87', 'pw1234', '임수현', '01036363737', 'soohyun87@example.com', '전라남도 순천시 조례동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('junghoon84', 'pw1234', '배정훈', '01038383939', 'junghoon84@example.com', '강원도 원주시 무실동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('seona93', 'pw1234', '서하늘', '01040404141', 'seona93@example.com', '충청북도 청주시 상당구 금천동');

INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('skyblue21', 'pw1234', '오지훈', '01041414242', 'skyblue21@example.com', '서울특별시 관악구 봉천동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('happy_jh', 'pw1234', '신지호', '01043434444', 'happyjh@example.com', '경기도 광명시 철산동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('yoon93', 'pw1234', '윤세민', '01045454646', 'yoon93@example.com', '부산광역시 사하구 당리동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('minji88', 'pw1234', '백민지', '01047474848', 'minji88@example.com', '대구광역시 달서구 감삼동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('hwan_07', 'pw1234', '조성환', '01049495050', 'hwan07@example.com', '인천광역시 계양구 계산동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('solbin12', 'pw1234', '이솔빈', '01051515252', 'solbin12@example.com', '광주광역시 광산구 수완동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('park_dy90', 'pw1234', '박도윤', '01053535454', 'parkdy90@example.com', '대전광역시 동구 판암동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('narae01', 'pw1234', '김나래', '01055555656', 'narae01@example.com', '울산광역시 중구 반구동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('smileysu', 'pw1234', '정수아', '01057575858', 'smileysu@example.com', '경기도 군포시 산본동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('lee_gh92', 'pw1234', '이건희', '01059596060', 'leegh92@example.com', '강원도 강릉시 교동');

INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('jiyoon_xx', 'pw1234', '최지윤', '01061616262', 'jiyoonxx@example.com', '충청북도 제천시 장락동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('dahyeok93', 'pw1234', '한다혁', '01063636464', 'dahyeok93@example.com', '경기도 평택시 합정동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('moon_lj', 'pw1234', '문예진', '01065656666', 'moonlj@example.com', '전라북도 군산시 수송동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('seung89', 'pw1234', '권승우', '01067676868', 'seung89@example.com', '경상북도 포항시 남구 이동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('hana95', 'pw1234', '송하나', '01069697070', 'hana95@example.com', '경상남도 창원시 마산회원구');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('kth_22', 'pw1234', '강태훈', '01071717272', 'kth22@example.com', '서울특별시 은평구 불광동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('prettyhj', 'pw1234', '허지민', '01073737474', 'prettyhj@example.com', '경기도 안산시 단원구 고잔동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('jo_ys01', 'pw1234', '조예슬', '01075757676', 'joys01@example.com', '부산광역시 북구 만덕동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('simplekm', 'pw1234', '김민정', '01077777878', 'simplekm@example.com', '대구광역시 북구 칠곡동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('leejae94', 'pw1234', '이재훈', '01079798080', 'leejae94@example.com', '경기도 성남시 수정구 신흥동');

INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('seulgi12', 'pw1234', '강슬기', '01081818282', 'seulgi12@example.com', '서울특별시 중랑구 면목동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('namsoo85', 'pw1234', '남수현', '01083838484', 'namsoo85@example.com', '경기도 고양시 일산서구 주엽동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('arin99', 'pw1234', '오아린', '01085858686', 'arin99@example.com', '충청남도 아산시 배방읍');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('byul_star', 'pw1234', '정별이', '01087878888', 'byulstar@example.com', '강원도 원주시 단계동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('kangmh91', 'pw1234', '강민혁', '01089899090', 'kangmh91@example.com', '경기도 김포시 구래동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('sujin07', 'pw1234', '이수진', '01091919292', 'sujin07@example.com', '서울특별시 동대문구 장안동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('happyhj', 'pw1234', '김하준', '01093939494', 'happyhj@example.com', '경기도 의정부시 민락동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('yoona33', 'pw1234', '윤아름', '01095959696', 'yoona33@example.com', '경상북도 구미시 인동동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('leejh02', 'pw1234', '이진호', '01097979898', 'leejh02@example.com', '서울특별시 동작구 사당동');
INSERT INTO member (id, pw, name, phone, email, addr) VALUES ('daon23', 'pw1234', '최다온', '01099991010', 'daon23@example.com', '경기도 하남시 신장동');

-- 도서관 정보 입력
INSERT INTO library_info(library_name, tel, location, operating_hour, closed_date)
VALUES('스마트 도서관', '051.2345.8765', '부산광역시 충렬대로 84', '09:00 ~ 18:00', '매달 둘째 주 월요일');

UPDATE library_info SET location = '부산광역시 동래구 충렬대로 84';
commit