 -- 일반 사용자 계정을 만들 수 있도록 내부 설정 변경
ALTER session set "_ORACLE_SCRIPT"=TRUE;

-- 프로젝트용 계정 생성
CREATE USER final_project IDENTIFIED BY 12345
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- 권한 부여
GRANT CONNECT, RESOURCE TO final_project;

-----------------------------------------------------------

-- 파이썬으로 생성
CREATE TABLE upcoming_books (
    num 		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title 		VARCHAR2(500),
    author 		VARCHAR2(200),
    publisher 	VARCHAR2(300),
    p_date 		Date,
    book_type 	VARCHAR2(100),
    img_src 	VARCHAR2(500),
    link 		VARCHAR2(500)
)

-- 회원 정보 테이블
CREATE TABLE member(
	mno		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 회원 번호
	id		VARCHAR2(50) NOT NULL UNIQUE,									-- 아이디
	pw		VARCHAR2(50) NOT NULL,											-- 비밀번호
	name	VARCHAR2(50) NOT NULL,											-- 이름
	phone	VARCHAR2(20),													-- 전화번호
	email 	VARCHAR2(100) NOT NULL,											-- 이메일
	addr	VARCHAR2(200),													-- 주소
	info	char(1), 														-- 개인 정보 이용 동의 여부
	status	char(1) DEFAULT 'Y'												-- 계정 활성화 여부(기본: 'Y', 탈퇴: 'N')
);

-- 전체 조회
SELECT * FROM member;

-- 테이블 제거
DROP TABLE member PURGE;

-- 도서 정보 테이블
CREATE TABLE book(
	bno				NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 도서 번호
	title			VARCHAR2(200) NOT NULL,												-- 제목
	author			VARCHAR2(50) NOT NULL,												-- 저자
	publisher		VARCHAR2(100) NOT NULL,												-- 발행 기관
	p_date			NUMBER(4),															-- 발행 연도
	cover			VARCHAR2(200),														-- 표지 이미지 경로
	is_available	VARCHAR2(20) DEFAULT 'AVAILABLE',									-- 대출 가능 여부(기본: 대출 가능, 대출 중인 경우: 불가능 'UNAVAILABLE')
	b_status		char(1) DEFAULT 'Y'													-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM book;

-- 테이블 제거
DROP TABLE book PURGE;

-- 도서 대출 테이블
CREATE TABLE book_loan(
	loan_no			NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 대출 번호
	bno				NUMBER NOT NULL REFERENCES book(bno),								-- 도서 번호
	user_id			VARCHAR2(50) NOT NULL REFERENCES member(id),						-- 대출자 아이디
	loan_status		VARCHAR2(50) DEFAULT 'BORROWED',									-- 대출 상태(기본: 대출 중, 반납 시 'RETURNED' / 추후 예약 기능 추가 가능)
	borrow_date 	DATE DEFAULT SYSDATE NOT NULL,										-- 대출일
	return_date 	DATE																-- 반납일
);

-- 전체 조회
SELECT * FROM book_loan;

-- 테이블 제거
DROP TABLE book_loan PURGE;

-- 이달의 도서 테이블
CREATE TABLE book_of_the_month(
	bom_no		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 번호 PK	
	bno			NUMBER REFERENCES book(bno),										-- 도서 번호
	title		VARCHAR2(200) NOT NULL,												-- 제목
	author		VARCHAR2(50) NOT NULL,												-- 저자
	publisher	VARCHAR2(100) NOT NULL,												-- 발행 기관
	p_date		NUMBER(4),															-- 발행 연도
	cover		VARCHAR2(200),														-- 표지 이미지 경로
	bom_status	char(1) DEFAULT 'Y'													-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM book_of_the_month;

-- 테이블 제거
DROP TABLE book_of_the_month PURGE;

-- 스터디룸 정보 테이블
CREATE TABLE studyroom(
	sno		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,		-- 스터디룸 번호
	s_name	VARCHAR2(50)														-- 스터디룸 이름(스터디룸 1, 스터디룸 2, ... 스터디룸 6 / 추후 스터디룸 추가 가능) 
);

-- 전체 조회
SELECT * FROM studyroom;

-- 테이블 제거
DROP TABLE studyroom PURGE;

-- 스터디룸 예약 테이블
CREATE TABLE studyroom_reservation(
	rno		 		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 예약 번호
	sno		 		NUMBER NOT NULL REFERENCES studyroom(sno),						-- 스터디룸 번호
	user_id	 		VARCHAR2(50) NOT NULL REFERENCES member(id),					-- 예약자 아이디
	user_name 		VARCHAR2(50) NOT NULL,											-- 예약자 이름
	reserve_date	DATE NOT NULL,													-- 예약 희망일
	apply_date		DATE DEFAULT SYSDATE NOT NULL,									-- 예약 신청일
	status			VARCHAR2(50) DEFAULT 'PENDING'									-- 예약 상태(기본: 대기 /승인, 거절, 취소) 
);

-- 전체 조회
SELECT * FROM studyroom_reservation;

-- 테이블 제거
DROP TABLE studyroom_reservation PURGE;

-- 공지 사항 저장 테이블
CREATE TABLE notice(
	nno				NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 공지 번호
	n_title			VARCHAR2(200) NOT NULL,											-- 제목
	n_author		VARCHAR2(50) NOT NULL,											-- 작성자 이름(관리자)
	n_content		CLOB,															-- 공지 내용
	n_create_date	DATE DEFAULT SYSDATE NOT NULL,									-- 작성 시간
	n_status		char(1) DEFAULT 'Y'												-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM notice;

-- 테이블 제거
DROP TABLE notice PURGE;

-- 건의 사항 게시글 저장 테이블
CREATE TABLE suggestion(
	sug_no			NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 건의 게시글 번호
	s_title			VARCHAR2(200) NOT NULL,											-- 제목
	s_userid		VARCHAR2(50) NOT NULL REFERENCES member(id),					-- 작성자 아이디
	s_author		VARCHAR2(50) NOT NULL,											-- 작성자 이름
	s_content		CLOB,															-- 건의 내용
	s_create_date	DATE DEFAULT SYSDATE NOT NULL,									-- 작성 시간
	s_update_date	DATE,															-- 수정 시간
	s_status		char(1) DEFAULT 'Y'												-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM suggestion;

-- 테이블 제거
DROP TABLE suggestion PURGE;

-- 건의 사항 댓글 저장 테이블
CREATE TABLE suggestion_reply(
	rpl_no			NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,	-- 
	sug_no			NUMBER NOT NULL REFERENCES suggestion(sug_no),					-- 건의 게시글 번호
	user_id			VARCHAR2(50) NOT NULL REFERENCES member(id),											-- 댓글 작성자 아이디(관리자 or 글 작성자)
	content			CLOB,															-- 댓글 내용
	rpl_create_date DATE DEFAULT SYSDATE NOT NULL,									-- 작성 시간
	rpl_update_date	DATE,															-- 수정 시간
	rpl_status		char(1) DEFAULT 'Y'												-- 상태(삭제 시 'N')
);

-- 전체 조회
SELECT * FROM suggestion_reply;

-- 테이블 제거
DROP TABLE suggestion_reply PURGE;

-- 도서관 정보 테이블
CREATE TABLE library_info(
	library_name	VARCHAR2(100) NOT NULL,			-- 도서관 이름
	tel				VARCHAR2(50) NOT NULL,			-- 전화 번호
	location		VARCHAR2(200) NOT NULL,			-- 위치
	operating_hour	VARCHAR2(100) NOT NULL,			-- 이용 시간
	closed_date		VARCHAR2(200) NOT NULL			-- 휴관일 정보
);

-- 전체 조회
SELECT * FROM library_info;

-- 테이블 제거
DROP TABLE library_info PURGE;

